configMapGenerator:
- files:
  - application.yml
  name: t82265683-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: t82265683
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/t82265683
  newTag: "202410090700"
- name: cepgstapacr.azurecr.io/t82265683
  newTag: "202410230644"
